name: Remote Desktop Free Google VM

on:
  workflow_dispatch:

jobs:
  start-desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Setup CRD + XFCE
        run: |
          sudo apt update
          sudo apt install --assume-yes wget curl nano
          sudo apt install --assume-yes xfce4 xfce4-goodies
          sudo apt install --assume-yes xrdp
          
          # Install Google Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install --assume-yes ./google-chrome-stable_current_amd64.deb || sudo apt --fix-broken install -y

          # Install Chrome Remote Desktop
          wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
          sudo dpkg -i chrome-remote-desktop_current_amd64.deb || sudo apt --fix-broken install -y

          # Setup CRD
          sudo usermod -a -G chrome-remote-desktop $USER
          echo "exec startxfce4" > ~/.xsession
          
          # Jalankan perintah CRD dari Google
          DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0AUJR-x5HcJzHxS3kD-dhEbMTJpDXDgMTV9sNkGt76qn_1I1S_4WdSVEt3EXOgPPVxAH45A" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)

          # Tetap hidup 6 jam
          sleep 21600
          
