name: Free RDP Ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup RDP
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies xrdp
          sudo systemctl enable xrdp
          
          # Tambah user 'rakwci' kalau belum ada
          id -u rakwci &>/dev/null || sudo adduser --disabled-password --gecos "" rakwci
          echo 'rakwci:123456' | sudo chpasswd
          sudo usermod -aG sudo rakwci

          sudo systemctl start xrdp
          curl ifconfig.me
          sleep 21600

